using System;

namespace ArcadeBot.Core.Entities.Guilds
{
    [Flags]
    public enum GuildFeature : long
    {
        None = 0L,
        AnimatedBanner = 1L << 0,
        AnimatedIcon = 1L << 1,
        Banner = 1L << 2,
        ChannelBanner = 1L << 3,
        Commerce = 1L << 4,
        Community = 1L << 5,
        Discoverable = 1L << 6,
        DiscoverableDisabled = 1L << 7,
        EnabledDiscoverableBefore = 1L << 8,
        Featureable = 1L << 9,
        ForceRelay = 1L << 10,
        HasDirectoryEntry = 1L << 11,
        Hub = 1L << 12,
        InternalEmployeeOnly = 1L << 13,
        InviteSplash = 1L << 14,
        LinkedToHub = 1L << 15,
        MemberProfiles = 1L << 16,
        MemberVerificationGateEnabled = 1L << 17,
        MonetizationEnabled = 1L << 18,
        MoreEmoji = 1L << 19,
        MoreStickers = 1L << 20,
        News = 1L << 21,
        NewThreadPermissions = 1L << 22,
        Partnered = 1L << 23,
        PremiumTier3Override = 1L << 24,
        PreviewEnabled = 1L << 25,
        PrivateThreads = 1L << 26,
        RelayEnabled = 1L << 27,
        RoleIcons = 1L << 28,
        RoleSubscriptionsAvailableForPurchase = 1L << 29,
        RoleSubscriptionsEnabled = 1L << 30,
        SevenDayThreadArchive = 1L << 31,
        TextInVoiceEnabled = 1L << 32,
        ThreadsEnabled = 1L << 33,
        ThreadsEnabledTesting = 1L << 34,
        ThreadsDefaultAutoArchiveDuration = 1L << 35,
        ThreeDayThreadArchive = 1L << 36,
        TicketedEventsEnabled = 1L << 37,
        VanityUrl = 1L << 38,
        Verified = 1L << 39,
        VIPRegions = 1L << 40,
        WelcomeScreenEnabled = 1L << 41,
        DeveloperSupportServer = 1L << 42,
        InvitesDisabled = 1L << 43,
        AutoModeration = 1L << 44,
        RaidAlertsDisabled = 1L << 45,
        ClydeEnabled = 1L << 46,
        GuildWebPageVanityUrl = 1L << 47
    }
}